import bpy
import os

# 翻译字典
_translations = {
    'zh_CN': {
        'E_Motion': 'E_Motion',
        'E_Motion Tools': 'E_Motion 工具',
        'Bezier Editor': '贝塞尔编辑器',
        'Edit': '编辑',
        'Curve Glow': '曲线发光',
        'Disable Glow': '禁用发光',
        'Enable Glow': '启用发光',
        'Curve Tools': '曲线工具',
        'Delete Empty Curves': '删除空曲线',
        'Delete All Modifiers': '删除所有修改器',
        'Frame Control': '帧控制',
        'Current Frame': '当前帧',
        'Jump to Start': '跳转到开头',
        'Jump to End': '跳转到结尾',
        'Interpolation Type': '插值类型',
        'Interpolation': '插值',
        'Easing': '缓动',
        'Dynamic Effects': '动态效果',
        'Apply Curve': '应用曲线',
        'Reset': '重置',
        'Mirror': '镜像',
        'Save Preset': '保存预设',
        'Zoom In': '放大+',
        'Zoom Out': '缩小-',
        'Center': '居中',
        'Manual Edit Control Points': '手动编辑控制点',
        'Operation Tips': '操作提示',
        'Click to enter edit mode': '点击进入编辑模式',
        'Drag blue (H1) and orange (H2) control points': '拖拽蓝色(H1)和橙色(H2)控制点',
        'Press ESC to exit edit mode': '按ESC退出编辑模式',
        'Adjust parameters and click Apply Curve': '调整参数后点击应用曲线到选中的关键帧',
        'Click interpolation type buttons to open pie menu': '点击插值类型按钮打开pie菜单选择插值模式',
        'Edit Mode': '编辑模式',
        'Active Object': '活动对象',
        'Active Modifier': '活动修改器',
        'Active Bezier Curve': '活动贝塞尔曲线',
        'Modifier Parameters': '修改器参数',
        'Type': '类型',
        'Restrict Frame Range': '限制帧范围',
        'Frame Start': '帧开始',
        'Frame End': '帧结束',
        'Additive Mode': '叠加模式',
        'Function Type': '函数类型',
        'Amplitude': '振幅',
        'Phase': '相位',
        'Frequency': '频率',
        'Offset': '偏移',
        'Scale': '缩放',
        'Strength': '强度',
        'Seed': '种子',
        'Noise Basis': '噪声基础',
        'Noise Scale': '噪声缩放',
        'Frame Step': '步长',
        'Interpolation': '插值',
        'Minimum X': '最小 X',
        'Maximum X': '最大 X',
        'Minimum Y': '最小 Y',
        'Maximum Y': '最大 Y',
        'Use Minimum X': '使用最小 X',
        'Use Maximum X': '使用最大 X',
        'Use Minimum Y': '使用最小 Y',
        'Use Maximum Y': '使用最大 Y',
        'Before': '循环前',
        'After': '循环后',
        'Control Points': '控制点',
        'Point': '点',
        'Frame': '帧',
        'Value': '值',
        'Other Parameters': '其他参数',
        'No Active Animation Data': '无活动动画数据',
        'Exit Edit Mode': '退出编辑模式',
        'Constant': '常量',
        'Linear': '线性',
        'Bezier': '贝塞尔',
        'Sine': '正弦',
        'Quadratic': '二次型',
        'Cubic': '三次型',
        'Quartic': '四次型',
        'Quintic': '五次型',
        'Exponential': '指数型',
        'Circular': '圆状',
        'Back': '回弹',
        'Bounce': '弹跳',
        'Elastic': '弹性',
    },
    'en_US': {
        'E_Motion': 'E_Motion',
        'E_Motion Tools': 'E_Motion Tools',
        'Bezier Editor': 'Bezier Editor',
        'Edit': 'Edit',
        'Curve Glow': 'Curve Glow',
        'Disable Glow': 'Disable Glow',
        'Enable Glow': 'Enable Glow',
        'Curve Tools': 'Curve Tools',
        'Delete Empty Curves': 'Delete Empty Curves',
        'Delete All Modifiers': 'Delete All Modifiers',
        'Frame Control': 'Frame Control',
        'Current Frame': 'Current Frame',
        'Jump to Start': 'Jump to Start',
        'Jump to End': 'Jump to End',
        'Interpolation Type': 'Interpolation Type',
        'Interpolation': 'Interpolation',
        'Easing': 'Easing',
        'Dynamic Effects': 'Dynamic Effects',
        'Apply Curve': 'Apply Curve',
        'Reset': 'Reset',
        'Mirror': 'Mirror',
        'Save Preset': 'Save Preset',
        'Zoom In': 'Zoom In',
        'Zoom Out': 'Zoom Out',
        'Center': 'Center',
        'Manual Edit Control Points': 'Manual Edit Control Points',
        'Operation Tips': 'Operation Tips',
        'Click to enter edit mode': 'Click to enter edit mode',
        'Drag blue (H1) and orange (H2) control points': 'Drag blue (H1) and orange (H2) control points',
        'Press ESC to exit edit mode': 'Press ESC to exit edit mode',
        'Adjust parameters and click Apply Curve': 'Adjust parameters and click Apply Curve',
        'Click interpolation type buttons to open pie menu': 'Click interpolation type buttons to open pie menu',
        'Edit Mode': 'Edit Mode',
        'Active Object': 'Active Object',
        'Active Modifier': 'Active Modifier',
        'Active Bezier Curve': 'Active Bezier Curve',
        'Modifier Parameters': 'Modifier Parameters',
        'Type': 'Type',
        'Restrict Frame Range': 'Restrict Frame Range',
        'Frame Start': 'Frame Start',
        'Frame End': 'Frame End',
        'Additive Mode': 'Additive Mode',
        'Function Type': 'Function Type',
        'Amplitude': 'Amplitude',
        'Phase': 'Phase',
        'Frequency': 'Frequency',
        'Offset': 'Offset',
        'Scale': 'Scale',
        'Strength': 'Strength',
        'Seed': 'Seed',
        'Noise Basis': 'Noise Basis',
        'Noise Scale': 'Noise Scale',
        'Frame Step': 'Frame Step',
        'Interpolation': 'Interpolation',
        'Minimum X': 'Minimum X',
        'Maximum X': 'Maximum X',
        'Minimum Y': 'Minimum Y',
        'Maximum Y': 'Maximum Y',
        'Use Minimum X': 'Use Minimum X',
        'Use Maximum X': 'Use Maximum X',
        'Use Minimum Y': 'Use Minimum Y',
        'Use Maximum Y': 'Use Maximum Y',
        'Before': 'Before',
        'After': 'After',
        'Control Points': 'Control Points',
        'Point': 'Point',
        'Frame': 'Frame',
        'Value': 'Value',
        'Other Parameters': 'Other Parameters',
        'No Active Animation Data': 'No Active Animation Data',
        'Exit Edit Mode': 'Exit Edit Mode',
        'Constant': 'Constant',
        'Linear': 'Linear',
        'Bezier': 'Bezier',
        'Sine': 'Sine',
        'Quadratic': 'Quadratic',
        'Cubic': 'Cubic',
        'Quartic': 'Quartic',
        'Quintic': 'Quintic',
        'Exponential': 'Exponential',
        'Circular': 'Circular',
        'Back': 'Back',
        'Bounce': 'Bounce',
        'Elastic': 'Elastic',
    },
    'ja_JP': {
        'E_Motion': 'E_Motion',
        'E_Motion Tools': 'E_Motion ツール',
        'Bezier Editor': 'ベジエエディター',
        'Edit': '編集',
        'Curve Glow': 'カーブグロー',
        'Disable Glow': 'グローを無効にする',
        'Enable Glow': 'グローを有効にする',
        'Curve Tools': 'カーブツール',
        'Delete Empty Curves': '空のカーブを削除',
        'Delete All Modifiers': 'すべてのモディファイアを削除',
        'Frame Control': 'フレーム制御',
        'Current Frame': '現在のフレーム',
        'Jump to Start': '先頭に移動',
        'Jump to End': '末尾に移動',
        'Interpolation Type': '補間タイプ',
        'Interpolation': '補間',
        'Easing': 'イージング',
        'Dynamic Effects': 'ダイナミックエフェクト',
        'Apply Curve': 'カーブを適用',
        'Reset': 'リセット',
        'Mirror': 'ミラー',
        'Save Preset': 'プリセットを保存',
        'Zoom In': '拡大+',
        'Zoom Out': '縮小-',
        'Center': 'センター',
        'Manual Edit Control Points': '制御点を手動で編集',
        'Operation Tips': '操作のヒント',
        'Click to enter edit mode': '編集モードに入るにはクリック',
        'Drag blue (H1) and orange (H2) control points': '青(H1)とオレンジ(H2)の制御点をドラッグ',
        'Press ESC to exit edit mode': 'ESCを押して編集モードを終了',
        'Adjust parameters and click Apply Curve': 'パラメーターを調整してカーブを適用',
        'Click interpolation type buttons to open pie menu': '補間タイプボタンをクリックしてパイメニューを開く',
        'Edit Mode': '編集モード',
        'Active Object': 'アクティブオブジェクト',
        'Active Modifier': 'アクティブモディファイア',
        'Active Bezier Curve': 'アクティブベジエカーブ',
        'Modifier Parameters': 'モディファイアパラメーター',
        'Type': 'タイプ',
        'Restrict Frame Range': 'フレーム範囲を制限',
        'Frame Start': 'フレーム開始',
        'Frame End': 'フレーム終了',
        'Additive Mode': '加算モード',
        'Function Type': '関数タイプ',
        'Amplitude': '振幅',
        'Phase': '位相',
        'Frequency': '周波数',
        'Offset': 'オフセット',
        'Scale': 'スケール',
        'Strength': '強度',
        'Seed': 'シード',
        'Noise Basis': 'ノイズベーシス',
        'Noise Scale': 'ノイズスケール',
        'Frame Step': 'フレームステップ',
        'Interpolation': '補間',
        'Minimum X': '最小X',
        'Maximum X': '最大X',
        'Minimum Y': '最小Y',
        'Maximum Y': '最大Y',
        'Use Minimum X': '最小Xを使用',
        'Use Maximum X': '最大Xを使用',
        'Use Minimum Y': '最小Yを使用',
        'Use Maximum Y': '最大Yを使用',
        'Before': '前',
        'After': '後',
        'Control Points': '制御点',
        'Point': 'ポイント',
        'Frame': 'フレーム',
        'Value': '値',
        'Other Parameters': 'その他のパラメーター',
        'No Active Animation Data': 'アクティブなアニメーションデータがありません',
        'Exit Edit Mode': '編集モードを終了',
        'Constant': '定数',
        'Linear': '線形',
        'Bezier': 'ベジエ',
        'Sine': 'サイン',
        'Quadratic': '二次',
        'Cubic': '三次',
        'Quartic': '四次',
        'Quintic': '五次',
        'Exponential': '指数',
        'Circular': '円形',
        'Back': 'バック',
        'Bounce': 'バウンス',
        'Elastic': 'エラスティック',
    },
    'ru_RU': {
        'E_Motion': 'E_Motion',
        'E_Motion Tools': 'Инструменты E_Motion',
        'Bezier Editor': 'Редактор Безье',
        'Edit': 'Редактировать',
        'Curve Glow': 'Сияние кривой',
        'Disable Glow': 'Отключить сияние',
        'Enable Glow': 'Включить сияние',
        'Curve Tools': 'Инструменты кривых',
        'Delete Empty Curves': 'Удалить пустые кривые',
        'Delete All Modifiers': 'Удалить все модификаторы',
        'Frame Control': 'Управление кадрами',
        'Current Frame': 'Текущий кадр',
        'Jump to Start': 'Перейти в начало',
        'Jump to End': 'Перейти в конец',
        'Interpolation Type': 'Тип интерполяции',
        'Interpolation': 'Интерполяция',
        'Easing': 'Плавность',
        'Dynamic Effects': 'Динамические эффекты',
        'Apply Curve': 'Применить кривую',
        'Reset': 'Сбросить',
        'Mirror': 'Отразить',
        'Save Preset': 'Сохранить пресет',
        'Zoom In': 'Увеличить+',
        'Zoom Out': 'Уменьшить-',
        'Center': 'Центр',
        'Manual Edit Control Points': 'Ручное редактирование контрольных точек',
        'Operation Tips': 'Советы по эксплуатации',
        'Click to enter edit mode': 'Нажмите, чтобы войти в режим редактирования',
        'Drag blue (H1) and orange (H2) control points': 'Перетащите синие (H1) и оранжевые (H2) контрольные точки',
        'Press ESC to exit edit mode': 'Нажмите ESC, чтобы выйти из режима редактирования',
        'Adjust parameters and click Apply Curve': 'Настройте параметры и нажмите Применить кривую',
        'Click interpolation type buttons to open pie menu': 'Нажмите кнопки типа интерполяции, чтобы открыть меню',
        'Edit Mode': 'Режим редактирования',
        'Active Object': 'Активный объект',
        'Active Modifier': 'Активный модификатор',
        'Active Bezier Curve': 'Активная кривая Безье',
        'Modifier Parameters': 'Параметры модификатора',
        'Type': 'Тип',
        'Restrict Frame Range': 'Ограничить диапазон кадров',
        'Frame Start': 'Начало кадра',
        'Frame End': 'Конец кадра',
        'Additive Mode': 'Адитивный режим',
        'Function Type': 'Тип функции',
        'Amplitude': 'Амплитуда',
        'Phase': 'Фаза',
        'Frequency': 'Частота',
        'Offset': 'Смещение',
        'Scale': 'Масштаб',
        'Strength': 'Сила',
        'Seed': 'Сид',
        'Noise Basis': 'Базис шума',
        'Noise Scale': 'Масштаб шума',
        'Frame Step': 'Шаг кадра',
        'Interpolation': 'Интерполяция',
        'Minimum X': 'Минимум X',
        'Maximum X': 'Максимум X',
        'Minimum Y': 'Минимум Y',
        'Maximum Y': 'Максимум Y',
        'Use Minimum X': 'Использовать минимум X',
        'Use Maximum X': 'Использовать максимум X',
        'Use Minimum Y': 'Использовать минимум Y',
        'Use Maximum Y': 'Использовать максимум Y',
        'Before': 'Перед',
        'After': 'После',
        'Control Points': 'Контрольные точки',
        'Point': 'Точка',
        'Frame': 'Кадр',
        'Value': 'Значение',
        'Other Parameters': 'Другие параметры',
        'No Active Animation Data': 'Нет активных анимационных данных',
        'Exit Edit Mode': 'Выйти из режима редактирования',
        'Constant': 'Постоянный',
        'Linear': 'Линейный',
        'Bezier': 'Безье',
        'Sine': 'Синус',
        'Quadratic': 'Квадратичный',
        'Cubic': 'Кубический',
        'Quartic': 'Четвертичный',
        'Quintic': 'Пятый степени',
        'Exponential': 'Экспоненциальный',
        'Circular': 'Круговой',
        'Back': 'Назад',
        'Bounce': 'Прыжок',
        'Elastic': 'Эластичный',
    },
}

# 获取当前语言
def get_language():
    import bpy
    # 首先检查插件偏好设置
    addon_prefs = bpy.context.preferences.addons.get('e_motion')
    if addon_prefs and hasattr(addon_prefs.preferences, 'language'):
        return addon_prefs.preferences.language
    
    # 读取Blender的语言设置
    blender_language = bpy.context.preferences.view.language
    
    # 根据Blender语言设置返回相应的语言代码
    if blender_language == 'zh_CN':
        return 'zh_CN'
    elif blender_language == 'ru_RU':
        return 'ru_RU'
    elif blender_language == 'ja_JP':
        return 'ja_JP'
    else:  # 英文或其他语言
        return 'en_US'

# 翻译函数
def _(text):
    lang = get_language()
    return _translations.get(lang, _translations['en_US']).get(text, text)

# 为了避免强制翻译，我们可以使用零宽字符
def _u(text):
    """添加零宽字符到文本中，避免强制翻译
    注意：只为非英文语言添加零宽字符，英文不添加
    """
    # 检查当前语言
    lang = get_language()
    
    # 英文不添加零宽字符
    if lang == 'en_US':
        return text
    
    # 为其他语言添加零宽字符
    result = ""
    for char in text:
        result += char + '\u200b'
    return result
